/*
-- Query: SELECT * FROM si_inventarios.Inventarios
-- Date: 2014-02-19 17:33
*/
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (1,NULL,'Pasteles','Fresa','Hecho de leche',120.00,13,2,10,'2013-01-01','Producto','Pieza');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (2,NULL,'Pasteles','Vainilla','Hecho de leche',127.00,15,2,10,'2013-01-01','Producto','Pieza');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (3,NULL,'Pasteles','Chocolate','Hecho de leche',120.00,6,2,10,'2013-01-01','Producto','Pieza');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (4,NULL,'Pasteles','Nuez','Hecho de leche',100.00,9,1,10,'2013-01-01','Producto','Pieza');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (5,NULL,'Pasteles','Selva Negra','Pan seco',130.00,15,3,10,'2013-01-01','Producto','Pieza');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (6,NULL,'Pasteles','Suizo','Pan seco',140.00,15,3,10,'2013-01-01','Producto','Pieza');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (7,NULL,'Galletas','Chocolate','Con chispas',20.00,15,4,20,'2013-01-01','Producto','Paquete');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (8,NULL,'Galletas','Glaseadas','Con Nuez',28.00,21,5,20,'2013-01-01','Producto','Paquete');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (9,NULL,'Galletas','Vainilla','...',17.00,22,3,20,'2013-01-01','Producto','Paquete');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (10,NULL,'Muffins','Chocolate','Con chispas de chocolate blanco',15.00,10,2,15,'2013-01-01','Producto','Pieza');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (11,NULL,'Muffins','Amapola','De la buena',18.00,14,5,15,'2013-01-01','Producto','Pieza');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (12,NULL,'CupCakes','Red Velvet','Terciopelo Rojo',26.00,20,5,20,'2013-01-01','Producto','Pieza');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (13,NULL,'Pays','Menta con Chocolate','Menta...',130.00,25,5,25,'2013-01-01','Producto','Pieza');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (14,NULL,'Pays','Queso','Queso crema',25.00,20,5,25,'2013-01-01','Producto','Pieza');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (15,NULL,'Pays','Limon','Limon dulce',22.00,20,4,25,'2013-01-01','Producto','Pieza');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (16,20,'MP','Leche','Ultrapasteurizada',12.90,50,10,40,'2013-01-01','MateriaPrima','Litros');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (17,22,'MP','Harina','Harina blanca',11.20,50,10,30,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (18,44,'MP','Huevo','18 piezas',32.20,50,15,40,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (19,1,'MP','Crema chatillí','5kg por carton',75.00,40,10,25,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (20,10,'MP','Azucar','Azucar morena agranel',14.90,80,20,90,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (21,28,'MP','Mantequilla','Con sal',93.00,50,30,80,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (22,33,'MP','Levadura','Royal',17.45,5,2,6,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (23,3,'MP','Cacao','Hershys',45.76,5,2,6,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (24,16,'MP','Chocolate','Amargo',60.00,5,2,6,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (25,33,'MP','Nuez','Moscada',72.00,8,3,6,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (26,7,'MP','Vainilla','Extracto',33.80,5,1,2,'2013-01-01','MateriaPrima','Litros');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (27,21,'MP','Piña','En almibar',38.89,4,1,2,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (28,38,'MP','Durazno','En almibar',43.50,4,1,2,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (29,46,'MP','Fresa','Pico de pàjaro',34.67,12,4,8,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (30,15,'MP','Queso crema','-------',79.00,8,3,6,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (31,18,'MP','Manzana','Red delicious',18.30,6,2,4,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (32,12,'MP','Menta','Extracto',130.00,2,1,1,'2013-01-01','MateriaPrima','Litros');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (33,28,'MP','Azùcar glass','Ultrafina',13.45,4,2,2,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (34,9,'MP','Limon','Concentrado',65.00,3,1,2,'2013-01-01','MateriaPrima','Litros');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (35,36,'MP','Semilla de amapola','Importada',67.80,2,1,1,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (36,22,'MP','Sal','La Fina',7.00,5,2,3,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (37,22,'MP','Bicarbonato de sodio','Puro',16.00,2,1,2,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (38,36,'MP','Chispas de chocolate','Semiamargo',37.00,4,2,3,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (39,10,'MP','Canela','En polvo',60.00,1,1,1,'2013-01-01','MateriaPrima','Kilogramos');
INSERT INTO `Inventarios` (`id_articulo`,`id_proveedor`,`categoria`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`tipo_articulo`,`unidad`) VALUES (40,32,'MP','Colorante rojo','Para red velvet',27.50,1,1,1,'2013-01-01','MateriaPrima','Kilogramos');
